### ISSUE TITLE
Create a prototype design in Figma

### ISSUE THREAD

**Issue by ramziddin** [ramziddin/find-my-coworking#6]
### Task description
Create a basic design for home and co-working pages.

### Acceptance criteria
- [ ] Find inspiration online
- [ ] Create a basic home page design
- [ ] Create a basic co-working page design
